### ISSUE TITLE
too many files open

### ISSUE THREAD

**Issue by gerardomachadoi** [v2fly/docker#45]
Hi,
Please help me. I am getting this error.
How to fix it with Docker
I want many people to access my server.

![Screenshot 2022-11-25 203134](https://user-images.githubusercontent.com/92561996/204025943-acc94b10-cf61-44c4-bb6d-b778a04b4134.png)

**Comment by sgqy** [comment]
in your docker compose.
```yaml
services:
  v2ray:
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
```
this may only work when `docker.service` set `LimitNOFILE=infinity` or a big number.
